[package]
name = "debrepobuilder"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]

[[bin]]
name = "debrep"
path = "src/main.rs"

[dependencies]
serde = "1.0.43"
toml = "0.4.6"
serde_derive = "1.0.43"
failure = "0.1.1"
failure_derive = "0.1.1"
reqwest = "0.8.5"
rayon = "1.0.1"
tempdir = "0.3.7"
xz2 = "0.1.4"
deflate = { version = "0.7.18", features = ["gzip"] }
select = "0.4.2"
glob = "0.2.11"
libc = "0.2"
clap = "2.32.0"
walkdir = "2.1.4"
log = { version = "0.4.3" }
sha2 = "0.7.1"
fern = "0.5.6"

[build-dependencies]
vergen = "0.1.1"
