archive = "bionic"
version = "18.04"
origin = "system76-example"
label = "Pop!_OS Example"
email = "michael@system76.com"

[[direct]]
name = "atom-editor"
version = "1.26.0"
arch = "amd64"
url = "https://atom-installer.github.com/v1.26.0/atom-amd64.deb"

# [[direct]]
# name = "atom-editor-beta"
# version = "1.27.0-beta0"
# arch = "amd64"
# url = "https://github.com/atom/atom/releases/download/v1.27.0-beta0/atom-amd64.deb"

[[direct]]
name = "mattermost-desktop"
version = "4.0.1"
arch = "amd64"
url = "https://releases.mattermost.com/desktop/4.0.1/mattermost-desktop-4.0.1-linux-amd64.deb"

[[direct]]
name = "slack-desktop"
version = "3.1.1"
arch = "amd64"
url = "https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.1-amd64.deb"

[[direct]]
name = "spotify-client"
version = "1.0.79.223.g92622cc2-21"
arch = "amd64"
url = "http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.79.223.g92622cc2-21_amd64.deb"

[[direct]]
name = "code"
version = "1.22.2-1523551015"
arch = "amd64"
url = "https://az764295.vo.msecnd.net/stable/3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9/code_1.22.2-1523551015_amd64.deb"

[[direct]]
name = "peek"
version = "1.3.1-0~ppa23"
arch = "amd64"
url = "http://ppa.launchpad.net/peek-developers/stable/ubuntu/pool/main/p/peek/peek_1.3.1-0~ppa23~ubuntu18.04.1_amd64.deb"

[[direct]]
name = "signal-desktop"
version = "1.8.0"
arch = "amd64"
url = "https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_1.8.0_amd64.deb"

[[direct]]
name = "google-chrome-stable"
version = "66.0.3359.139-1"
arch = "amd64"
url = "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

[[direct]]
name = "steam"
version = "1.0.0.54"
arch = "i386"
url = "http://us.archive.ubuntu.com/ubuntu/pool/multiverse/s/steam/steam_1.0.0.54+repack-5ubuntu1_i386.deb"

[[direct]]
name = "steam-installer"
version = "1.0.0.54"
arch = "all"
url = "http://us.archive.ubuntu.com/ubuntu/pool/multiverse/s/steam/steam-installer_1.0.0.54+repack-5ubuntu1_all.deb"

[[direct]]
name = "steam-devices"
version = "1.0.0.54"
arch = "all"
url = "http://us.archive.ubuntu.com/ubuntu/pool/multiverse/s/steam/steam-devices_1.0.0.54+repack-5ubuntu1_all.deb"

[[direct]]
name = "android-studio"
version = "173.4720617"
arch = "amd64"
url = "http://ppa.launchpad.net/maarten-fonville/android-studio/ubuntu/pool/main/a/android-studio/android-studio_173.4720617~bionic_amd64.deb"

[[direct]]
name = "android-studio-preview"
version = "181.4720098"
arch = "amd64"
url = "http://ppa.launchpad.net/maarten-fonville/android-studio/ubuntu/pool/main/a/android-studio-preview/android-studio-preview_181.4720098~bionic_amd64.deb"

#[[source]]
#name = "peek"
#version = "1.3.1"
#cvs = "git"
#url = "https://github.com/phw/peek"
#prebuild = ["git checkout origin/debian-packaging -- debian/"]
