archive = "bionic"
version = "18.04"
origin = "system76-example"
label = "Pop!_OS Example"
email = "michael@system76.com"

[[direct]]
name = "atom-editor"
version = "1.26.0"
arch = "amd64"
url = "https://atom-installer.github.com/v1.26.0/atom-amd64.deb"

[[direct]]
name = "atom-editor-beta"
version = "1.27.0-beta0"
arch = "amd64"
url = "https://github.com/atom/atom/releases/download/v1.27.0-beta0/atom-amd64.deb"

[[direct]]
name = "mattermost-desktop"
version = "4.0.1"
arch = "amd64"
url = "https://releases.mattermost.com/desktop/4.0.1/mattermost-desktop-4.0.1-linux-amd64.deb"

[[direct]]
name = "slack-desktop"
version = "3.1.1"
arch = "amd64"
url = "https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.1-amd64.deb"

[[direct]]
name = "spotify-client"
version = "1.0.79.223.g92622cc2-21"
arch = "amd64"
url = "http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.79.223.g92622cc2-21_amd64.deb"

[[direct]]
name = "code"
version = "1.22.2-1523551015"
arch = "amd64"
url = "https://az764295.vo.msecnd.net/stable/3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9/code_1.22.2-1523551015_amd64.deb"

[[source]]
name = "peek"
version = "1.3.1"
url = "https://github.com/phw/peek"
